version: "3.9"

services:
  smartrent-api:
    build: . # Dockerfile ရှိတဲ့ folder (လက်ရှိ folder)
    image: hteinlinaung/smartrent:latest
    container_name: smartrent-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=smartrent_db;Username=postgres;Password=mypassword123
      - Jwt__Key=YourSuperSecretKey_MustBeLong_12345!
      - Jwt__Issuer=SmartRent
      - Jwt__Audience=SmartRentUsers
    depends_on:
      db:
        condition: service_healthy
    networks:
      - smartrent-net

  db:
    image: postgres:15 # Alpine မဟုတ်တဲ့ Full version ကို သုံးလိုက်တာက ပိုပြီး Robust (ခိုင်ခံ့) ပါတယ်
    container_name: postgres-db
    restart: always
    shm_size: 128mb # Shared memory ကို သတ်မှတ်ပေးခြင်းက Linux ပေါ်မှာ ပိုမြန်စေတယ်
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword123
      POSTGRES_DB: smartrent_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d smartrent_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - smartrent-net

networks:
  smartrent-net:
    driver: bridge

volumes:
  postgres_data: