version: "3.9"

services:
  smartrent-api:
    image: hteinlinaung/smartrent:latest
    container_name: smartrent-api
    ports:
      - "8080:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=smartrent_db;Username=postgres;Password=mypassword
    depends_on:
      db:
        condition: service_healthy
    networks:
      - smartrent-net

  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: smartrent_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - smartrent-net

networks:
  smartrent-net:
    driver: bridge

volumes:
  postgres_data:
